### ISSUE TITLE
小程序登录验证

### ISSUE THREAD

**Issue by xuluchun8** [EastWorld/wechat-app-mall#104]
![snip20180820_17](https://user-images.githubusercontent.com/26465186/44320107-8aff1500-a472-11e8-8180-0e156521e63b.png)
学习小程序，想学习您的这个mall, 但是这个怎么验证不了呀 ，请教一下这个是怎么回事？谢谢

**Comment by gooking** [comment]
请看 README 的详细说明，有具体的解决方法
