### ISSUE TITLE
真机调试下拉刷新无法反弹回去得bug

### ISSUE THREAD

**Issue by djspys1** [EastWorld/wechat-app-mall#111]
在全局配置文件中使用`"enablePullDownRefresh":true,`时，会引发一些bug，
比如在我的页面、购物车页面等地方，在模拟器时没有问题，但是在真机调试时，下拉后不会反弹回去，会在顶部留一段空白

解决办法有二个，一个是取消全局的下拉刷新，在首页需要的地方进行手动配置
第二个是在每个页面配置如下代码:
```
  onPullDownRefresh: function() {
    wx.stopPullDownRefresh()
  }
```
或者直接在json文件中加入
`"enablePullDownRefresh": false`

**Comment by gooking** [comment]
全局 enablePullDownRefresh 已改为页面 enablePullDownRefresh，感谢分享！

**Comment by gooking** [comment]
感谢分享！ enablePullDownRefresh 从全局改为 页面定义。
