### ISSUE TITLE
后端服务

### ISSUE THREAD

**Issue by bokire** [EastWorld/wechat-app-mall#113]
大家用的后端都是自己开发的吗？有好的合适的开源项目推荐吗？

**Comment by talway** [comment]
odoo  需要安装接口插件，可对接进销存，功能强大。

**Comment by talway** [comment]
https://github.com/JoneXiong/oejia_weshop

http://www.oejia.net/blog/2018/10/18/oejia_weshop_v012.html

**Comment by gooking** [comment]
这3个开源的还不错的：

https://github.com/tumobi/nideshop
https://www.oschina.net/p/freeter-admin
https://www.oschina.net/p/OdnShop
