### ISSUE TITLE
app.js中的登陆方法是 写在onLaunch中的，只在小程序启动时会自动登陆，若是启动一段时间后（例如浏览了两个页面后）登陆失效需要重新登录的，貌似没做这个处理

### ISSUE THREAD

**Issue by Mirrur-Lin** [EastWorld/wechat-app-mall#117]
_Originally posted by @Mirrur-Lin in https://github.com/EastWorld/wechat-app-mall/issue_comments#issuecomment-435253729_

**Comment by gooking** [comment]
会跳转到授权页面~
