### ISSUE TITLE
Bugs: fslse should be false. 造成了该隐藏的按钮没有隐藏

### ISSUE THREAD

**Issue by billibit** [EastWorld/wechat-app-mall#126]
wechat-app-mall/pages/order-list/index.wxml
      
                <view class="btn cancel-btn" hidden="{{item.status==0? fslse : true}}" bindtap="cancelOrderTap"  data-id="{{item.id}}">取消订单</view>
			                <view class="btn topay-btn" hidden="{{item.status==0? fslse : true}}" bindtap="toPayTap" data-id="{{item.id}}" data-money="{{item.amountReal}}" data-score="{{item.score}}">马上付款</view>

**Comment by gooking** [comment]
非常感谢，已经 fix
