### ISSUE TITLE
登陆后台成功后如何获得返回的token？

### ISSUE THREAD

**Issue by billibit** [EastWorld/wechat-app-mall#127]
尝试调用 后台API进行 用户管理。 
1. 用 商户号和秘钥实现登录，以获取token

/login/key  POST

成功后 并没有看到哪儿返回任何token。 是需要注册成为VIP才可以吗？
{
  "code": 1000000,
  "data": {
    "dateAdd": "2018-11-16 10:36:24",
    "domain": "fd8cd5ea272a",
    "id": 10333,
    "lastVisitDate": "2018-11-29 00:56:19",
    "merchantKey": "ee08f0....",
    "merchantNo": "1....",
    "mobile": 137....,
    "pwd": "f....28178c",
    "realName": "xxxxxx",
    "salt": "1zdRoE",
    "status": 0,
    "statusStr": "正常",
    "type": 0,
    "vipLevel": 0
  },
  "msg": "vip用户开放"
}
2. GET管理员详情
/user/admin/info
{
  "code": 100000,
  "msg": "请先登录"
}

**Comment by gooking** [comment]
需要 vip
