### ISSUE TITLE
request url封装

### ISSUE THREAD

**Issue by luo201227** [EastWorld/wechat-app-mall#132]
将所有请求的url独立抽离封装起来就更完美了，不知道有没有这个计划

**Comment by gooking** [comment]
精力有限，希望能有更多的人加入一起维护

**Comment by luo201227** [comment]
众人拾柴火焰高，开源就是希望就是借助社区的力量不断重壮大孵化项目；另外也可以截效果图吸引更多开发者加入

**Comment by luo201227** [comment]
> 这项目的确是有很多可以改进的地方，接口请求我可以封装一下，不过我没有后台账号，所以页面上还是得你们自己调用测试，在首页调用banner的时候会写个例子

看来提交的一版本，觉得不仅仅需要将域名基本路径提取封装，还应该将各请求接口路径也实现抽离，代码中只负责调用封装后属性，更有利于维护请求链接

**Comment by djspys1** [comment]
> > 这项目的确是有很多可以改进的地方，接口请求我可以封装一下，不过我没有后台账号，所以页面上还是得你们自己调用测试，在首页调用banner的时候会写个例子
> 
> 看来提交的一版本，觉得不仅仅需要将域名基本路径提取封装，还应该将各请求接口路径也实现抽离，代码中只负责调用封装后属性，更有利于维护请求链接

你意思是加一个service部分，然后页面引入对应的service模块，再在页面使用类似service.getDetail()这种方式获取数据？

**Comment by luo201227** [comment]
> > > 这项目的确是有很多可以改进的地方，接口请求我可以封装一下，不过我没有后台账号，所以页面上还是得你们自己调用测试，在首页调用banner的时候会写个例子
> > 
> > 
> > 看来提交的一版本，觉得不仅仅需要将域名基本路径提取封装，还应该将各请求接口路径也实现抽离，代码中只负责调用封装后属性，更有利于维护请求链接
> 
> 你意思是加一个service部分，然后页面引入对应的service模块，再在页面使用类似service.getDetail()这种方式获取数据？

目前项目分层也是很重要的，没有足够的精力的话，可以先将url先全部映射出来

**Comment by gooking** [comment]
已完工，感谢 @djspys1
