### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by liguangze** [EastWorld/wechat-app-mall#140]
“无法登录” / Token 无效 ？

app.js 里面的 subDomain 改成你自己的，保存；
登录你的小程序后台（MP那个地址），Request 域名处增加 api.it120.cc
确保小程序后台（MP那个地址） 的appid，工厂后台填写的 appid ，开发工具右上角 “项目详情” 打开后显示的 appid ，这3个 appid 是一模一样的；
开发工具上点击 “清除缓存” —> “编译”

app.js 并没有 subDomain    config.js 里面才有subDomain     是不是写错了呢，
刚刚研究小程序， config.js里面也改了还是无法登陆

MP那个地址的那个地址是哪个地址，

工厂后台填写的 appid ，这个在哪里，没有找到啊

**Comment by gooking** [comment]
对的，写错了

**Comment by yangfff** [comment]
嗯嗯好哒好哒，谢谢！

发件人：gooking <notifications@github.com>
发送日期：2019-01-17 17:57:47
收件人：EastWorld/wechat-app-mall <wechat-app-mall@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re: [EastWorld/wechat-app-mall] 无法登陆 (#140)
对的，写错了
