### ISSUE TITLE
微信小程序将不再支持部分功能

### ISSUE THREAD

**Issue by wangzhenjjcn** [EastWorld/wechat-app-mall#146]
你好，微信小程序将不再支持如下功能：获得用户分享成功与否事件，wx.getUserInfo接口弹窗授权，wx.openSetting接口自动打开设置页。10月10日起，当你的小程序发布新版本后，上述能力将无法在新版本使用。请务必检查确认小程序已完成调整，不会影响线上服务。

/pages/authorize/index.js  Line 130  Line 129

**Comment by djspys1** [comment]
他这项目的登录页是自己写的，通过用户手动点击获取信息，不影响。
微信影响的是进入小程序后，用户未做任何操作就弹出授权框的情况
