### ISSUE TITLE
首页选中商品类别的时候居中用户体验会好点

### ISSUE THREAD

**Issue by HoneyJt** [EastWorld/wechat-app-mall#152]
/**
   * 选中某一个类别
   */
  tabClick:function(e){
    console.log(e)
    var offset = e.currentTarget.offsetLeft;
    if(offset>150){
      offset = offset - 150
    }else{
      offset = 0;
    }
    this.setData({
      activeCategoryId: e.currentTarget.id,
      curPage:1,
      cateScrollTop:offset
    })
    this.getGoodsList(this.data.activeCategoryId)
  },

wxml中设置scroll-left="{{cateScrollTop}}"属性即可实现

**Comment by gooking** [comment]
感谢您的无私奉献，已将您的代码合并~
