### ISSUE TITLE
商品发布接口

### ISSUE THREAD

**Issue by makeapp007** [EastWorld/wechat-app-mall#159]
请问是否有接口提供给商品发布？在商品管理中没有找到。

**Comment by gooking** [comment]
后台接口中有商品发布接口，仅针对vip用户开放

https://user.api.it120.cc/doc.html

发自我的 iPhone

**Comment by makeapp007** [comment]
已经是vip了。可以给个具体的例子吗？比如针对商品修改，post的url是 https://api.it120.cc/user/apiExtShopGoods/save吗？显示接口不存在。

**Comment by makeapp007** [comment]
post的url是https://api.it120.cc/rentabroad/user/apiExtShopGoods/save？目前遇到bug的是请先登录。请问如何传递/login/key后的token?

**Comment by makeapp007** [comment]
解决了。把登陆后的token赋给X-Token，然后放到header里即可。

**Comment by gooking** [comment]
vip就加我微信 gooking 


发自我的 iPhone
