### ISSUE TITLE
是否考虑支持1对多模式

### ISSUE THREAD

**Issue by pengjugame** [EastWorld/wechat-app-mall#173]
1个服务器对应多家商铺，同时又对应1个API床。
用户进入后，可以选择一个商铺再进去。
这样就可以管理多家商铺了。

不知道之后会不会考虑有这种支持？
或者我在wechat-app-mall的基础上，大概做些什么内容。

**Comment by gooking** [comment]
api接口和后台支持，小程序端的代码你自己改一下就好了
