### ISSUE TITLE
无法直接进入商品详情页，盼回复

### ISSUE THREAD

**Issue by goomoon** [EastWorld/wechat-app-mall#175]
现在在公众号菜单中只能通过pages/index/index 直接进入首页，而无法通过pages/goods-details/index.html?id=144938 直接进入商品详情页，会报页面不存在的错误；这个有办法调整实现吗，不然在公众号想放一些直达商品detail的菜单，无法实现

**Comment by gooking** [comment]
建议亲先了解一些微信小程序开发的基础，当前开源项目需要有一定的小程序基础的
