### ISSUE TITLE
商品详情页从“客服”返回会反复在“选择：”后面加单位

### ISSUE THREAD

**Issue by baitian3744** [EastWorld/wechat-app-mall#178]
商品详情页（pages/goods-details/index.js第101行），selectSize: that.data.selectSize + selectSizeTemp, 比如在选择“客服“然后再回退回来的时候，会导致不停的在后面加单位，比如：“选择： 箱”，到“选择：箱 箱“，再到“选择：箱 箱 箱”。。。其他回退到该页面数据不刷新的情况应该都会导致这个，目前只发现这种情况。

**Comment by gooking** [comment]
感谢反馈。
期待高人可以贡献代码，修复该bug

**Comment by baitian3744** [comment]
这个我改了，你看下

**Comment by gooking** [comment]
十分感谢 @baitian3744
