### ISSUE TITLE
config.js中为什么不需要设置api工厂的商户密钥？

### ISSUE THREAD

**Issue by tcgdy0201** [EastWorld/wechat-app-mall#182]
如题。
是不是意味着人家只需要改了同样的二级域名，就可以无需鉴权来调用后台api？

**Comment by gooking** [comment]
小程序代码是前端代码，任何直接在小程序代码上填写敏感信息的行为都是耍流氓！

你知道小程序源码是可以被下载的么？那么你写的商户秘钥不就暴露了么？
