### ISSUE TITLE
为啥后台代码不开源？

### ISSUE THREAD

**Issue by Joe192168** [EastWorld/wechat-app-mall#183]
有商业版吗

**Comment by gooking** [comment]
你好：

并非后台代码不开源，是没有后台！
本项目是100%的小程序开源项目，我们没有开发当前小程序的配套后台，因为 api工厂 提供的接口和后台已经足够强大，足够满足我们的需求，我们就完全没有必要去开发后台了。

当然，如果你不喜欢使用 api工厂 ，你也完全可以根据小程序中使用到的api接口，自行开发一个后台，期待你与大家分享！

**Comment by gooking** [comment]
你可以去百度了解一下  API工厂 ，有了这个产品，暂时没有理由说服我们自己去开发后台，直接用他们的省心省力。
