### ISSUE TITLE
checkHasLogined方法 checksession未作await处理？

### ISSUE THREAD

**Issue by whutyzy** [EastWorld/wechat-app-mall#187]
`async function checkHasLogined() {
  const token = wx.getStorageSync('token')
  if (!token) {
    return false
  }
  wx.checkSession({
    fail() {
      return false
    }
  })
  const checkTokenRes = await WXAPI.checkToken(token)
  if (checkTokenRes.code != 0) {
    wx.removeStorageSync('token')
    return false
  }
  return true
}`
checkSession是一个异步的方法，我理解应该用promise包装一下然后await?

**Comment by gooking** [comment]
你可以自己动手试试看~
