### ISSUE TITLE
微信登录好像有新要求了 现在可能过不了审

### ISSUE THREAD

**Issue by Quekie** [EastWorld/wechat-app-mall#190]
为更好地保护用户隐私信息，优化用户体验，小程序需提供合理的用户帐号登录功能，请参照《小程序内用户帐号登录规范调整和优化建议》进行检查并做出调整。自2019年9月1日起，平台将会在小程序代码审核环节对不符合登录规范的帐号审核进行拦截。
https://developers.weixin.qq.com/community/operate/doc/000640bb8441b82900e89f48351401

**Comment by gooking** [comment]
最新代码已经按照微信的要求调整好了，直接用就可以了
