### ISSUE TITLE
基于这段代码修改后能否申请软著？

### ISSUE THREAD

**Issue by ahuzwb** [EastWorld/wechat-app-mall#191]
您好，最近我们希望基于您的代码来完成一个公益商城的小程序，不知道我们修改后的代码能否申请软著

**Comment by gooking** [comment]
软著怎么可能是属于你们的呢？这是个开源软件，请知悉，你们自行去申请软著本身就是一种侵权行为，请慎重

**Comment by ahuzwb** [comment]
不好意思啊，对这方面实在不够了解




------------------ 原始邮件 ------------------
发件人: "gooking"<notifications@github.com>; 
发送时间: 2019年10月21日(星期一) 下午3:28
收件人: "EastWorld/wechat-app-mall"<wechat-app-mall@noreply.github.com>; 
抄送: "2933001480"<2933001480@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [EastWorld/wechat-app-mall] 基于这段代码修改后能否申请软著？ (#191)




软著怎么可能是属于你们的呢？这是个开源软件，请知悉，你们自行去申请软著本身就是一种侵权行为，请慎重
