### ISSUE TITLE
点击分类或搜索时不跳转

### ISSUE THREAD

**Issue by ITdakaWGY** [EastWorld/wechat-app-mall#195]
我通过后台把分类的图标跟名字换了一下，然后在小程序中，点击分类后，index页面不会跳转，只会类似于刷新一下。
我在后台给商品添加了关键词标签，然后使用搜索时，也是没有跳转，只在index页面刷新了一下，请问是我哪里改的有错误，请教一下

**Comment by ITdakaWGY** [comment]
现在，点击分类时跳转了，但是搜索还是不行..........

**Comment by ITdakaWGY** [comment]
我明明加了关键词标签，但是搜索关键词时并不会在商品列表显示，而且搜索商品全称时也没有搜到

**Comment by ITdakaWGY** [comment]
我发现问题了，因为我之前点击过分类标签，搜索时只在此标签下进行搜索了....而我搜索的商品并没有在此标签下
现在的问题是，我在点击分类标签之后，怎样操作才可以再次显示所有商品，而不是只显示此分类下的商品呢

**Comment by gooking** [comment]
设计如此，你的需求，可以根据你自己的期望相应的修改小程序代码得以实现
