### ISSUE TITLE
本机调试和真机调试正常，手机预览无照片

### ISSUE THREAD

**Issue by fengyanzhang** [EastWorld/wechat-app-mall#199]
![微信图片_20191219222741](https://user-images.githubusercontent.com/5967397/71181283-ce5bd480-22ae-11ea-96a0-e1386c1b802d.jpg)
![微信图片_20191219222746](https://user-images.githubusercontent.com/5967397/71181285-cef46b00-22ae-11ea-9840-f7fad5ea350b.jpg)
![微信图片_20191219222749](https://user-images.githubusercontent.com/5967397/71181286-cf8d0180-22ae-11ea-9e80-802940093186.jpg)

**Comment by gooking** [comment]
README 中有说明的，接口域名没设置 https://www.yuque.com/apifm/doc/tvpou9
