### ISSUE TITLE
关于优惠买单功能

### ISSUE THREAD

**Issue by Mavlan** [EastWorld/wechat-app-mall#203]
能否问题下优惠买单功能为何不能使用账户余额来买单？

**Comment by gooking** [comment]
应该是可以的，你再确认一下，可能是你还没有余额吧

**Comment by Mavlan** [comment]
> 应该是可以的，你再确认一下，可能是你还没有余额吧

谢谢您的回答 是可以 但是就是最终控制台会显示总的余额和扣除的余额 但就是小程序里和后台里都没有扣除记录 还是显示的原来的余额

**Comment by gooking** [comment]
加我微信  gooking ， 我帮你看看

**Comment by gooking** [comment]
https://github.com/EastWorld/wechat-app-mall/commit/d6f80436f8e08e79e9af7dd4fe552af44ce53732

是传参的bug，已修复，按照上面的指引修改即可
