### ISSUE TITLE
请指教：商品添加购物车失败

### ISSUE THREAD

**Issue by pacteralhw** [EastWorld/wechat-app-mall#207]
请问商品添加购物车后提示“请提交sku参数”是什么原因？

**Comment by gooking** [comment]
你没有选择商品的 sku 就去添加购物车了，估计是你修改代码后出现的问题，你可以加我微信  gooking 我帮你看看

**Comment by wmforum** [comment]
不好意思，我也是从git上复制来的，不是原作者，您继续找找吧……
----- 原始邮件 -----
发件人：pacteralhw <notifications@github.com>
收件人：EastWorld/wechat-app-mall <wechat-app-mall@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[EastWorld/wechat-app-mall]_请指教：商品添加购物车失败_(#207)
日期：2020年02月03日 22点47分

请问商品添加购物车后提示“请提交sku参数”是什么原因？



&mdash;
