### ISSUE TITLE
请问这个问题出现是为什么？

### ISSUE THREAD

**Issue by hangfiu** [EastWorld/wechat-app-mall#232]
VM2807:1 Failed to load image https://cdn.it120.cc/apifactory/2018/01/10/ebb1129f26d6a5968fcb81cc19055e41.jpg
the server responded with a status of 404 (HTTP/1.1 404 Not Found) 
From server 117.24.12.139
报了很多类似的错误。

**Comment by gooking** [comment]
图片不存在，应该是后台把这个图片删除了
