### ISSUE TITLE
后端服务购买

### ISSUE THREAD

**Issue by Yudezhi** [EastWorld/wechat-app-mall#239]
请问购买后端服务后，如何保证商家的数据安全？

**Comment by gooking** [comment]
你好，本项目是一个开源的纯小程序的项目，完全免费，无需支付任何费用！
本项目是纯前端的小程序项目，没有开发接口及后台部分的程序，而是直接使用的 api工厂 的在线 saas 产品的。
您可以免费使用我们的开源小程序项目，然后自行去开发实现接口和后台。
如果你也选择使用 api工厂 ，具体事宜，请自行联系他们进行咨询，谢谢！
