### ISSUE TITLE
关于手机预览的问题

### ISSUE THREAD

**Issue by LiuYuNan01** [EastWorld/wechat-app-mall#242]
微信开发者工具下可以正常运行   预览生成的二维码在手机上面就有问题 
1.首页什么内容都没有
2.点击分类一直转圈
3.授权登录的时候 点击运行卡死 

我的是iphonex

**Comment by Airtonium** [comment]
我也是这样子，开发者工具下可以运行，真机调试也正常，但是真机预览和发布体验版就和楼主一样的问题。
已经确认域名、appid和request合法域名都是正确的。

**Comment by gooking** [comment]
请配置合法域名 

https://www.it120.cc/help/tvpou9.html
