### ISSUE TITLE
compile and preview后在手机微信上无商品内容

### ISSUE THREAD

**Issue by geneva0901** [EastWorld/wechat-app-mall#248]
微信开发者工具上app运行正常，但编译预览在手机上无法正常显示内容，截图如下：
![IMG_20200927_204754](https://user-images.githubusercontent.com/5820451/94365358-d7fa4e80-0102-11eb-8d81-6aa14fab44f7.jpg)

谢谢开发者：）

**Comment by gooking** [comment]
请按教程操作
