### ISSUE TITLE
优惠券显示有一些问题

### ISSUE THREAD

**Issue by 666-yeah** [EastWorld/wechat-app-mall#249]
比如后台优惠券设置20%off，但小程序前端却显示¥20，实际上结算的时候金额确实是按照8折计算的，但是优惠金额显示的是-20，与实际情况不符，希望修复这个问题。

**Comment by gooking** [comment]
感谢反馈，已修复：

**Comment by gooking** [comment]
https://github.com/EastWorld/wechat-app-mall/commit/f7b864e499ed66d491e2f3277a0b53c14fdd6e9d
