### ISSUE TITLE
门店自取下单的时候，能不能让客户输入电话和姓名

### ISSUE THREAD

**Issue by gxy022** [EastWorld/wechat-app-mall#254]
门店自取下单的时候，能不能让客户输入电话和姓名？
有些货品需要主动跟客户确认，如果没有客户的电话，就不方便！

**Comment by gooking** [comment]
感谢反馈，已添加：

https://github.com/EastWorld/wechat-app-mall/commit/520380cac0398e9025b983f2aef2ca5bc871a76e
