### ISSUE TITLE
金额没有4省5入

### ISSUE THREAD

**Issue by xudeliang** [EastWorld/wechat-app-mall#255]
![WechatIMG361](https://user-images.githubusercontent.com/583680/100974740-c6587b80-3577-11eb-9fee-01636419092e.jpeg)
![WechatIMG362](https://user-images.githubusercontent.com/583680/100974741-c6f11200-3577-11eb-8a5d-6ff4c1d8d2b7.jpeg)

**Comment by gooking** [comment]
感谢反馈，已修复：
https://github.com/EastWorld/wechat-app-mall/commit/a28f90ae56a7a3b756699eb5113820efca09d3fb
