### ISSUE TITLE
自提订单 联系方式 问题

### ISSUE THREAD

**Issue by gxy022** [EastWorld/wechat-app-mall#256]
上次自提订单增加了联系人和电话
但二次下单的时候，联系人是空的，能否把之前的订单联系人和电话调出来，省去重新填写的步骤

**Comment by gooking** [comment]
目前是会默认读取当前用户绑定的手机号码的。如果不是绑定的手机号码，而是直接填写的话，第二次不会默认出来，建议您可以把输入框做成自读的，需要用户通过后面的 “自动获取” 按钮获取
