### ISSUE TITLE
怎么跑起来，我npm run test 没用啊

### ISSUE THREAD

**Issue by Mrmangmang** [EastWorld/wechat-app-mall#259]

**Comment by binglongworld** [comment]
人家这是原生小程序，不是vue



---原始邮件---
发件人: "Mrmangmang"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 下午4:08
收件人: "EastWorld/wechat-app-mall"<wechat-app-mall@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [EastWorld/wechat-app-mall] 怎么跑起来，我npm run test 没用啊 (#259)

**Comment by Mrmangmang** [comment]
那我怎么把它跑起来呢

**Comment by binglongworld** [comment]
建议先看下微信公众平台的文档



---原始邮件---
发件人: "Mrmangmang"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 下午4:26
收件人: "EastWorld/wechat-app-mall"<wechat-app-mall@noreply.github.com&gt;;
抄送: "守望星空"<406266011@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [EastWorld/wechat-app-mall] 怎么跑起来，我npm run test 没用啊 (#259)




 
那我怎么把它跑起来呢
