### ISSUE TITLE
绑定手机号，提示没有权限

### ISSUE THREAD

**Issue by BUGyyc** [EastWorld/wechat-app-mall#265]
![image](https://user-images.githubusercontent.com/13402838/114198547-0ac0b180-9986-11eb-8ac7-13c7f6dfedfc.png)

appid等信息都是没有问题的，但是依然提示这个错误

**Comment by gooking** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html

**Comment by tanglong123456** [comment]
> https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html

**Comment by tanglong123456** [comment]
> ![图像](https://user-images.githubusercontent.com/13402838/114198547-0ac0b180-9986-11eb-8ac7-13c7f6dfedfc.png)
> 
> appid等信息都是没有问题的，但是依然提示这个错误

朋友，你解决这个问题了吗？我这边也遇到同样问题
