### ISSUE TITLE
商品列表页面加入购物车会提示当前商品没有SKU组合

### ISSUE THREAD

**Issue by LizhenZhang** [EastWorld/wechat-app-mall#277]
商品列表页面加入购物车会提示当前商品没有SKU组合，建议如果没有SKU的组合最好不要列出来，要不影响用户体验。

**Comment by gooking** [comment]
这个问题是因为你是sku设置错误导致的，不是前端的问题，请登陆后台，编辑商品，设置正确的 sku 信息（检查下是否重复配置了）
