### ISSUE TITLE
商品详情的评价显示不齐全

### ISSUE THREAD

**Issue by dynamicheart** [EastWorld/wechat-app-mall#279]
疑似滑不到最底部（Iphone 13 Pro MAX）
![WechatIMG7](https://user-images.githubusercontent.com/19570241/154911813-d16a69c5-5669-4109-9784-4a8dfb8fca20.jpeg)

**Comment by gooking** [comment]
https://github.com/EastWorld/wechat-app-mall/commit/40667a6d41baddb72791c082e17403c43c9211d4
