### ISSUE TITLE
下单收货地址能否实现自动读取微信中填写地址？

### ISSUE THREAD

**Issue by bitlin** [EastWorld/wechat-app-mall#28]
发现有别的小程序实现了授权后能自动获取地址

**Comment by WhiteYin** [comment]
可以吧，有wx.chooseAddress接口，获取用户授权后返回姓名邮编和收货地址

**Comment by gooking** [comment]
wx.chooseAddress  获取到的收货地址和系统后台发货的省市区编码不兼容；
为了达到小程序商城和H5版、Android、ios、pc版本的商城收货地址兼容，只能放弃微信提供的获取通讯地址接口功能
