### ISSUE TITLE
商品分类页面和商品详情页面的显示问题

### ISSUE THREAD

**Issue by dynamicheart** [EastWorld/wechat-app-mall#280]
问题一：在商品分类页面，含有多种型号的商品，在点击添加进购物车时，购买数量显示不全；

问题二：商品分类滑动到最下面，最后一个商品一开始会显示不全，然后再往下滑时，才能显示完全；

问题三：商品详情页面，在下滑到商品详情时，上面的tab调到了商品评价。

![111645582564_ pic](https://user-images.githubusercontent.com/19570241/155251808-70400898-1d5a-481c-aea5-4f4babfa2a80.jpg)
![121645582565_ pic](https://user-images.githubusercontent.com/19570241/155251804-1f823879-df13-4760-b3cc-5f8e1a50e75d.jpg)
![131645582565_ pic](https://user-images.githubusercontent.com/19570241/155251800-f5f8067e-5ea3-4d1a-970f-20853b48a6bb.jpg)

**Comment by gooking** [comment]
https://github.com/EastWorld/wechat-app-mall/commit/c6fa3c2bc775dc8bf6b8244a5b62d1b2416683ea
