### ISSUE TITLE
ios系统违规

### ISSUE THREAD

**Issue by ITdakaWGY** [EastWorld/wechat-app-mall#283]
你好，根据《微信小程序平台运营规范》14.6，除小游戏类目的安卓内购功能，开发者在iOS系统上提供的虚拟物品不能展现任何购买、支付的功能、页面、按钮，即使实际上它们都不可使用；也不得引导至外部网页或APP来实现支付功能。请对当前小程序内含有虚拟支付的内容或服务进行排查并整改。在整改完成前，暂不支持iOS用户打开该小程序。

请问这种问题改怎么修改程序，再次审核通过

**Comment by AnChaoYang** [comment]
不让干的咱不干，就可以啦

**Comment by gaofengIt** [comment]
您好，我已经收到您的邮件，将尽快给您回复。

**Comment by gooking** [comment]
这是你自己业务上的事情，你不要卖虚拟物品不就可以了么？和本项目无关
