### ISSUE TITLE
商品分类滑动到最下面，最后一个商品一开始会显示不全，然后再往下滑时，才能显示完全

### ISSUE THREAD

**Issue by hahalaughddd** [EastWorld/wechat-app-mall#284]
如标题所示
第280个问题中的，问题二还是没解决

**Comment by gooking** [comment]
可以录屏看一下么？

**Comment by hahalaughddd** [comment]
已发送至您的javazj@qq.com邮箱

**Comment by gooking** [comment]
你的专属域名是啥？我用你的专属域名调试一下看看


&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EastWorld/wechat-app-mall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 晚上11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EastWorld/wechat-app-mall] 商品分类滑动到最下面，最后一个商品一开始会显示不全，然后再往下滑时，才能显示完全 (Issue #284)





 
***@***.***邮箱

**Comment by hahalaughddd** [comment]
4d0266ff74cbd9ba8341cf9b1d8d592e
