### ISSUE TITLE
{"code":700,"msg":"暂无数据"}

### ISSUE THREAD

**Issue by wangchong321** [EastWorld/wechat-app-mall#289]
/config/values这个接口返回无数据，请问是我配置错误码？需要怎么配置。

**Comment by gooking** [comment]
建议您咨询一下api工厂那边，700 的状态码应该就是你后台没有配置系统参数吧

**Comment by zj2050** [comment]
> 建议您咨询一下api工厂那边，700 的状态码应该就是你后台没有配置系统参数吧

我也遇到这个问题，小程序页面一片空白， 没有提示任何参数错误
