### ISSUE TITLE
当前登录token无效，请重新登录

### ISSUE THREAD

**Issue by lovelyJason** [EastWorld/wechat-app-mall#292]
是登录不了吗？点头像登录不了

![Snipaste_2023-05-21_23-11-29](https://github.com/EastWorld/wechat-app-mall/assets/50656459/98b4dd8a-807c-4a0a-a3b3-6f3dfa5ee839)

擦是我api工厂后台没配置好，不好意思

**Comment by hankinghu** [comment]
我也是，报这个错
