### ISSUE TITLE
商品详情选择加入购物车，返回首页切换tab进购物车没有新增加的商品信息

### ISSUE THREAD

**Issue by WhiteYin** [EastWorld/wechat-app-mall#30]
建议修改shop-cart/index.js
![bug](https://user-images.githubusercontent.com/11420425/29993587-f9aafa5e-8fed-11e7-820b-2cc7a1b26661.png)

**Comment by gooking** [comment]
非常感谢，onshow 改为 onShow 解决~

大小写的问题，默认方法是 onShow
