### ISSUE TITLE
微信修改隐私协议，导致无法绑定手机

### ISSUE THREAD

**Issue by morehappy0** [EastWorld/wechat-app-mall#300]
现在新客户一选择绑定手机，就出现错误，无法下一步。
请问应该如何修改文件呢？有没有升级补丁呀？
感谢支持！
![error](https://github.com/EastWorld/wechat-app-mall/assets/15385588/79addccb-6cf8-4965-92ed-5a7a8da265c7)

**Comment by gooking** [comment]
https://www.zhuige.com/index/news/detail/id/1902.html

小程序后台更新一下用户隐私即可
