### ISSUE TITLE
图片和音频资源大小不应该超过200K，启用组件按需注入

### ISSUE THREAD

**Issue by WangMar** [EastWorld/wechat-app-mall#307]
第一次上传小程序，用的git上的包，显示了图片和音频资源大小不应该超过200K，启用组件按需注入，是需要自己压缩图片或者把图片换成图床的链接吗？

**Comment by gooking** [comment]
这是你自己开发小程序过程中遇到的问题，建议百度或者寻求微信官方帮助解决。直接运行本项目不存在你说的问题

**Comment by WangMar** [comment]
感谢回复。可我用的就是wechat-app-mall master的包，遇到了这个问题，非常的困惑。。

**Comment by HXB-1997** [comment]
一样的问题
