### ISSUE TITLE
订单详情可左右滑动

### ISSUE THREAD

**Issue by WhiteYin** [EastWorld/wechat-app-mall#31]
应该是某个view标签样式宽度超过屏幕宽度了
![bug](https://user-images.githubusercontent.com/11420425/29993687-7b0e4f90-8ff0-11e7-96d1-d24e1e2ce272.jpg)

**Comment by gooking** [comment]
复测存在该问题，寻求高手帮忙修复该 bug，修改后可直接提交修正代码

**Comment by zhangweihu** [comment]
商品详情页的商品详情图片也会左右滑动，商品详情页的底部的客服还有购物车这个两个有点问题，还有就是添加地址的时候地址列表展示不出来，

**Comment by gooking** [comment]
订单详情页面左右可滚动，已修复，请查看主线版本
