### ISSUE TITLE
测试发现问题不能调用优惠券信息

### ISSUE THREAD

**Issue by jincon** [EastWorld/wechat-app-mall#32]
使用1.4版本的测试，如果需要物流填写地址的那种，此时如果我已经优惠券了，但是在创建的订单 pages/to-pay-order/index
页面，不显示可用优惠券？如果我把商品设置不需要物流，就可以使用优惠券？ 这是bug？？

**Comment by jincon** [comment]
如果购买两个2商品，一个需要物流，一个个不需要物流，显示正常，但是购买单个需要物流的商品，却没法显示可用优惠券信息。

**Comment by gooking** [comment]
是不是您的订单总金额不满足使用优惠券的条件？亲，再帮忙测试下，如果 bug 存在，能否尝试帮忙调试修改呢？

**Comment by jincon** [comment]
肯定不是啊，一个不需要物流的商品，都能显示出来优惠券；我再加了另外一个需要物流的商品，当然这个商品也他的属性，但是就不显示了优惠券，也达到了金额。但是不显示可使用的优惠券
