### ISSUE TITLE
为什么在苹果6s，苹果7下都看不到图片？安卓机下正常

### ISSUE THREAD

**Issue by simon1026** [EastWorld/wechat-app-mall#33]
![_20170905122548](https://user-images.githubusercontent.com/7332436/30045223-7e96105c-9235-11e7-8a35-844470cce469.jpg)

**Comment by wilbyang** [comment]
遇到同样的问题

**Comment by gooking** [comment]
![image](https://user-images.githubusercontent.com/7286469/31651228-700337ba-b2e0-11e7-87c1-df801f19bd4a.png)
