### ISSUE TITLE
项目在本地跑报错求教~

### ISSUE THREAD

**Issue by deepthan** [EastWorld/wechat-app-mall#36]
错误结果如下：
WAService.js:3  里：
cthirdScriptError
Cannot read property 'value' of undefined;at App onLaunch function;at api request success callback function
TypeError: Cannot read property 'value' of undefined

WAService.js:3 thirdScriptError
Cannot read property 'length' of undefined;at pages/index/index onLoad function;at api request success callback function
TypeError: Cannot read property 'length' of undefined

项目在本地配置好api等信息后在首页显示这个错误，并且首页内容显示不出来，请帮忙看下，谢谢。

**Comment by gooking** [comment]
请下载最新版本，已经增加了比较好的提示，如有疑问，可以加QQ群，大家一起交流
