### ISSUE TITLE
机型：iphone6，7真机上联系人，手机号码等几个选项对其都有问题。

### ISSUE THREAD

**Issue by BluedRS** [EastWorld/wechat-app-mall#4]
模拟器上没有问题，可以对其。但是真机上，联系人，手机号码，详细地址，邮政编号，对其都有问题，无法剧中显示。希望大神改一下WXSS样式，小弟安卓，实在是乏力啊

**Comment by gooking** [comment]
感谢您的反馈，最新的主线版本已修复
