### ISSUE TITLE
排序功能出错

### ISSUE THREAD

**Issue by charles1256** [EastWorld/wechat-app-mall#41]
https://api.it120.cc/chenchanglin/shop/goods/list?orderBy=priceUp

**Comment by gooking** [comment]
您好！

您反应的问题，技术已核实，确实存在部分用户无法排序的问题。

现已修复，感谢您的支持！谢谢！

**Comment by gooking** [comment]
您好！

您反应的问题，技术已核实，确实存在部分用户无法排序的问题。

现已修复，感谢您的支持！谢谢！

**Comment by charles1256** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
目前依然存在部分数据没显示的情况，大额的金额没显示，测试url同上                



    在2017年11月10日 08:21，gooking<notifications@github.com> 写道： 


您好！
您反应的问题，技术已核实，确实存在部分用户无法排序的问题。
现已修复，感谢您的支持！谢谢！

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  






        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by charles1256** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
没问题了，我搞错了，对了，目前该小程序有没有只限定50条商品信息这样一条规定？

    在2017年11月10日 13:27，Charles<1184775757@qq.com> 写道： 




    font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
目前依然存在部分数据没显示的情况，大额的金额没显示，测试url同上                



    在2017年11月10日 08:21，gooking<notifications@github.com> 写道： 


您好！
您反应的问题，技术已核实，确实存在部分用户无法排序的问题。
现已修复，感谢您的支持！谢谢！

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  






        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
