### ISSUE TITLE
根据你的配置，设置了三个小时，一直报合法域名的问题

### ISSUE THREAD

**Issue by huguiqi** [EastWorld/wechat-app-mall#44]
![image](https://user-images.githubusercontent.com/490617/33496251-7589dbe2-d704-11e7-9ce4-be602237008a.png)
后台添加了商品，就是出不来，报这个错

小程序后台设置：

![image](https://user-images.githubusercontent.com/490617/33496305-acc9c6da-d704-11e7-9637-435ec6649efb.png)

**Comment by gooking** [comment]
重启一下你的开发工具，有缓存的

**Comment by huguiqi** [comment]
可以了，但我是个人开发者账号，都无法支付，能过审核吗？

发自我的 iPhone

**Comment by dreamfish797** [comment]
@huguiqi 你是怎么解决的

**Comment by huguiqi** [comment]
重启开发工具
