### ISSUE TITLE
设置了token，但验证不过又被置空

### ISSUE THREAD

**Issue by Thobian** [EastWorld/wechat-app-mall#45]
如题
subDomain、token 没有设置错
`{"code":10000,"msg":"token 无效，请重新登录"}`

另外顺带请教下另外个问题，后台显示的：平台商户号  这个是做什么用？

**Comment by gooking** [comment]
![image](https://user-images.githubusercontent.com/7286469/34335035-a1f53b06-e986-11e7-8618-8381ab11cfab.png)

登录问题，请看README.md 上图截图部分；

平台商户号和秘钥，是您在其他系统中对接工厂api时候使用的，和本商城应用没有太大关联性
