### ISSUE TITLE
购物车中点击"去结算"，控制台报错

### ISSUE THREAD

**Issue by ldbmcs** [EastWorld/wechat-app-mall#48]
购物车中点击"去结算"，控制台报错"Setting data field "orderType" to undefined is invalid."

**Comment by ldbmcs** [comment]
跟踪代码发现，to_pay_order/index中 onLoad(that.setData({isNeedLogistics: 1,orderType: e.orderType});)商品详情调到支付页面的时候带有orderType参数，购物车跳过去就不带参数，然后就出现underfined。
另外就是是否需要物流不是全局控制的嘛。为啥这里直接写死了？

**Comment by gooking** [comment]
分析后，并无你所说的问题，请确认您本地代码结构，是否您自行修改后出现了问题？
