### ISSUE TITLE
紧急bug！快递模板设置了不包邮，订单下单的时候会有问题

### ISSUE THREAD

**Issue by BluedRS** [EastWorld/wechat-app-mall#5]
快递模板设置了不包邮，例如：设置顺丰，一个件12，增加一个件6块钱。然后商品关联了快递模板正常下单，提交订单的时候，就会出现错误：未配置该快递类型，而且订单还显示包邮。要是快递模板设置包邮就没有问题。希望大神尽快解决，这个bug比较蛋疼

**Comment by BluedRS** [comment]
@gooking 大神一定要解决这个问题啊，这个问题很棘手啊！

**Comment by gooking** [comment]
您好，物流这个问题比较麻烦，建议您暂时在后台配置一个包邮的物流模板，快递费用加价到商品价格里面，通过这种方式暂时过渡一下

**Comment by gooking** [comment]
您好，您提交的BUG已修复，请下载 1.2.2 版本
