### ISSUE TITLE
修改globalData:{ userInfo:null, subDomain:"mall" }后访问不了服务器

### ISSUE THREAD

**Issue by Ycocol** [EastWorld/wechat-app-mall#62]
globalData:{ userInfo:null, subDomain:"mall" }

        subDomain 中的 mall 为上面您注册开通的域名

按照要求修改为我自己的域名，编译后请求不到数据了，跪求大神帮助。

**Comment by gooking** [comment]
看项目的 README 文档

**Comment by dreamfish797** [comment]
@Ycocol 请问你解决了吗，我也是改了mail后，然后一直报服务器错误，说地址不合法，微信后台也设置了
