### ISSUE TITLE
购物车下单时，异步造成的校验失败

### ISSUE THREAD

**Issue by cokepanm** [EastWorld/wechat-app-mall#7]
由于小程序框架不支持同步请求，这边在下单前做的校验的代码会因为引用对象不是之前赋值的对象而失效，如下代码
`toPayOrder:function(){
      wx.showLoading();
      var that = this;
      if (this.data.goodsList.noSelect) {
        return;
      }
      // 重新计算价格，判断库存
      var shopList = [];
      var shopCarInfoMem = wx.getStorageSync('shopCarInfo');
      if (shopCarInfoMem && shopCarInfoMem.shopList) {
        shopList = shopCarInfoMem.shopList
      }
      if (shopList.length == 0) {
        return;
      }
      var isFail = false;
      var doneNumber = 0;
      var needDoneNUmber = shopList.length;
      for (var i =0; i < shopList.length; i++) {
        if (isFail) {
          wx.hideLoading();
          return;
        }
        var carShopBean = shopList[i];`
这里carShopBean在请求的回调函数里早不是之前的对象了，因此回调函数里不能再引用了，解决方案参考这个http://www.cnblogs.com/limingxi/p/4048705.html

**Comment by gooking** [comment]
您好，非常感谢您的关注和建议，确实存在这个问题。
另：除了用闭包确实可以解决这个问题之外，还可以有另外一种更加方便的方法可以解决这个问题：

将原先定义变量时候的   var  关键词，改为   let  关键词。
