### ISSUE TITLE
后端接口的源码有考虑开源吗

### ISSUE THREAD

**Issue by firnsan** [EastWorld/wechat-app-mall#73]
请问后端接口的源码有考虑开源吗， 不开源是基于什么考虑？

**Comment by gooking** [comment]
您好：

非常感谢您对本项目的关注！
由于我们开发人员有限，当前项目暂时还没有配套的系统后台，我们团队开发的是小程序前端的商城项目；
后来辗转在网上发现了 api工厂 这个非常棒的云接口和后台平台，接口定义和和我们小程序商城的非常吻合，就直接用他们的后台和接口了的；
如果你们有兴趣开发一个后台的话，欢迎开源出来让大家一起来完善！

再次感谢！
