### ISSUE TITLE
关于保存用户登录态

### ISSUE THREAD

**Issue by TerminatorSd** [EastWorld/wechat-app-mall#90]
您好，看到您的代码里是用userInfo 是否存在来判断是否需要跳转到授权页面。但是userInfo 只有使用setStorage 设置过而没有removeStorage 的操作，也就是说一经设置一直存在。那这种方式是检测不到session_key 过期这个问题的吧，而只能靠用户手动点击重新登录按钮来刷新session_key。

**Comment by gooking** [comment]
不需要的，具体你可以进群交流

发自我的 iPhone

**Comment by gooking** [comment]
userInfo 和 token 一起保存在 Storage 中的，假如 token 过期了，是会自动重新登录的，你看下 app.js 的 登录方法

**Comment by Mirrur-Lin** [comment]
app.js中的登陆方法是 写在onLaunch中的，只在小程序启动时会自动登陆，若是启动一段时间后（例如浏览了两个页面后）登陆失效需要重新登录的，貌似没做这个处理
