### ISSUE TITLE
我是猎头刘康 电话18588511446

### ISSUE THREAD

**Issue by superliukang** [EastWorld/wechat-app-mall#91]
我在帮深圳的一家企业在找 小程序开发

薪酬预算40w以内 1年以上即可。

做 综艺内容为主的pgc模式的视频平台，是深圳著名手机硬件厂商的 内容尝试。

快快联系我吧！电话：18588511446

**Comment by gooking** [comment]
兄弟，你来错地方了，这里打广告不但没用，而且还容易让人对你的企业有不好的印象
